using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SmartTourBackend.Migrations
{
    /// <inheritdoc />
    public partial class AddDevicePresenceTracking : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE TABLE IF NOT EXISTS "DevicePresences" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "DeviceId" character varying(128) NOT NULL,
                    "LastSeenUtc" timestamp with time zone NOT NULL DEFAULT NOW(),
                    CONSTRAINT "PK_DevicePresences" PRIMARY KEY ("Id")
                );
                """);

            migrationBuilder.Sql("""
                ALTER TABLE "DevicePresences" ADD COLUMN IF NOT EXISTS "IpAddress" character varying(128) NOT NULL DEFAULT '';
                ALTER TABLE "DevicePresences" ADD COLUMN IF NOT EXISTS "UserAgent" character varying(512) NOT NULL DEFAULT '';
                ALTER TABLE "DevicePresences" ADD COLUMN IF NOT EXISTS "DeviceModel" character varying(128) NOT NULL DEFAULT '';
                ALTER TABLE "DevicePresences" ADD COLUMN IF NOT EXISTS "Platform" character varying(64) NOT NULL DEFAULT '';
                ALTER TABLE "DevicePresences" ADD COLUMN IF NOT EXISTS "OsVersion" character varying(64) NOT NULL DEFAULT '';
                ALTER TABLE "DevicePresences" ADD COLUMN IF NOT EXISTS "AppVersion" character varying(32) NOT NULL DEFAULT '';
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_DevicePresences_DeviceId" ON "DevicePresences" ("DeviceId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE "DevicePresences" DROP COLUMN IF EXISTS "IpAddress";
                ALTER TABLE "DevicePresences" DROP COLUMN IF EXISTS "UserAgent";
                ALTER TABLE "DevicePresences" DROP COLUMN IF EXISTS "DeviceModel";
                ALTER TABLE "DevicePresences" DROP COLUMN IF EXISTS "Platform";
                ALTER TABLE "DevicePresences" DROP COLUMN IF EXISTS "OsVersion";
                ALTER TABLE "DevicePresences" DROP COLUMN IF EXISTS "AppVersion";
                """);
        }
    }
}
